### ISSUE TITLE
return html 

### ISSUE THREAD

**Issue by wayneconnolly** [developer-rakeshpaul/scrapex#1]
Hi, I would like the html to be returned so I don't have to make a separate call for it.

const html = await site.text();

Thanks,
Wayne

**Comment by developer-rakeshpaul** [comment]
Hi Wayne,

it will be great If you could elaborate a little bit on the requirement. The scrape response contains a field "content" which returns the readability html for the page. if you are looking for the full html content of the page, I will add that to the response on the next release.

Kind Regards,
Rakesh

**Comment by wayneconnolly** [comment]
Hi, Sorry for the late response. Yes, I would like the full html also. This saves having to use another package to pull and analyse the url again. Really great work on scrapex by the way. It's very impressive how you pulled together the different packages and got it to work seamlessly.

**Comment by wayneconnolly** [comment]
Thank-you-I see it's there now.

**Comment by developer-rakeshpaul** [comment]
Thanks a lot Wayne for your kind words. Happy to know you find scrapex helpful.
